language: go
sudo: required
go:
    - tip
services:
    - docker
before_install:
    - go get github.com/tools/godep
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/stretchr/testify
    - go get github.com/mattn/goveralls
after_sucess:
    - go build
    - docker build -t ghmeier/towncenter
    - docker push ghmeier/towncenter
install:
    - godep restore
script:
    - $HOME/gopath/bin/goveralls -service=travis-ci
notifications:
  slack: mostlygifs:xU99ulMzejqNTJbFcBEWPCEF